hydra:
  run:
    dir: outputs

defaults:
  - model: mixtral_7b_train
  - data: hh_rlhf_cai


lora_config:
  r: 128
  lora_alpha: 64
  lora_dropout: 0.1
  bias: none
  task_type: CAUSAL_LM
  inference_mode: false
  target_modules:
  - q_proj
  - v_proj
  - k_proj
  - o_proj
  - w1
  - w2
  - w3
  - lm_head

wandb:
  project: scai
  log_model: checkpoint
  name: hh_rlhf_cai 

validation_split_size: 0.025

dpo_beta: 0.1
max_prompt_length: 612

training_args:
  output_dir: /scr/jphilipp/scai/trained_models/Mixtral-8x7B-v0.1/checkpoints/16bit
  evaluation_strategy: steps  
  eval_steps: 500
  warmup_steps: 150 
  per_device_train_batch_size: 8
  per_device_eval_batch_size: 8
  gradient_accumulation_steps: 8 
  logging_steps: 1
  logging_strategy: "steps"
  learning_rate: 1e-6 
  num_train_epochs: 2
  max_steps: 5000
  save_strategy: steps
  save_steps: 250
  save_total_limit: 20
  seed: 42
  report_to: wandb
  bf16: true
  remove_unused_columns: false


