hydra:
  run:
    dir: outputs

defaults:
  - model: mistral_7b_base
  - data: hh_rlhf

wandb:
  project: scai-tuning
  log_model: checkpoint
  name: sft_helpful_chosen

validation_split_size: 0.05

training_args:
  output_dir: /scr/jphilipp/scai/trained_models/Mistral-7B-v0.1/checkpoints/sft_helpful_chosen
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  gradient_accumulation_steps: 32
  learning_rate: 2.0e-05
  num_train_epochs: 4
  save_total_limit: 4
  evaluation_strategy: epoch
  seed: 42
  save_strategy: epoch
  report_to: wandb
  bf16: true
  lr_scheduler_type: cosine
  warmup_ratio: 0.1
  do_eval: true
  logging_steps: 5  
  logging_strategy: steps