wandb_version: 1

model:
  desc: null
  value:
    model_type: huggingface
    name: mistral_7b_base
    model_config:
      pretrained_model_name_or_path: mistralai/Mistral-7B-v0.1
      cache_dir: /scr/jphilipp/scai/pretrained_models/Mistral-7B-v0.1
    tokenizer_config:
      pretrained_model_name_or_path: mistralai/Mistral-7B-v0.1
      cache_dir: /scr/jphilipp/scai/pretrained_models/Mistral-7B-v0.1
      model_max_length: 2048
data:
  desc: null
  value:
    data_path: /scr/jphilipp/scai/datasets/hh-rlhf-pragmalign/training
    helpful: train-helpful-0-10k-iteration-0.json
    harmless: train-harmless-0-10k-iteration-0.json
    n_responses: 2
    n_constitutions: 2
wandb:
  desc: null
  value:
    project: pragmalign
    name: beta-0.5-iteration-1
pragmalign:
  desc: null
  value:
    beta: 0.5
    include_kl_softmax: true
training:
  desc: null
  value:
    evaluate_before_training: true
    n_epochs: 1
    lr: 1.0e-06
    train_batch_size: 1
    eval_batch_size: 1
    train_split: 0.95
    checkpoint_dir: /scr/jphilipp/scai/trained_models/Mistral-7B-v0.1/checkpoints/pragmalign-beta-0.5-iteration-1-0-5k
    max_grad_norm: 1.0
    num_warmup_steps: 1
    gradient_accumulation_steps: 32
    save_after_n_steps: 500
    seed: 42
    model_archive: null
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.0
    framework: huggingface
    huggingface_version: 4.37.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1709560105.254899
    t:
      1:
      - 1
      - 11
      - 49
      - 50
      - 51
      - 55
      - 71
      - 105
      2:
      - 1
      - 11
      - 49
      - 50
      - 51
      - 55
      - 71
      - 105
      3:
      - 13
      - 16
      - 23
      4: 3.10.13
      5: 0.16.0
      6: 4.37.2
      8:
      - 5
      13: linux-x86_64
