wandb_version: 1

model:
  desc: null
  value:
    model_type: huggingface
    name: mistral_7b_base
    model_config:
      pretrained_model_name_or_path: mistralai/Mistral-7B-v0.1
      cache_dir: /scr/jphilipp/scai/pretrained_models/Mistral-7B-v0.1
    tokenizer_config:
      pretrained_model_name_or_path: mistralai/Mistral-7B-v0.1
      cache_dir: /scr/jphilipp/scai/pretrained_models/Mistral-7B-v0.1
      model_max_length: 2048
data:
  desc: null
  value:
    data_path: hh_rlhf/data
    helpful: train-helpful-0-10k-iteration-0-no-sorry-positive.json
    harmless: train-harmless-0-10k-iteration-0-no-sorry-positive.json
    n_responses: 2
    n_constitutions: 2
wandb:
  desc: null
  value:
    project: sft-no-sorry-positive
    log_model: checkpoint
    name: sft-iteration-1-no-sorry-positive
training_args:
  desc: null
  value:
    output_dir: /scr/jphilipp/scai/trained_models/Mistral-7B-v0.1/checkpoints/sft-iteration-1-no-sorry-positive
    per_device_train_batch_size: 2
    per_device_eval_batch_size: 2
    gradient_accumulation_steps: 16
    learning_rate: 1.0e-06
    num_train_epochs: 1
    save_total_limit: 1
    evaluation_strategy: 'no'
    seed: 42
    save_strategy: epoch
    report_to: wandb
    bf16: true
    warmup_steps: 150
    lr_scheduler_type: linear
    do_eval: true
    logging_steps: 5
    logging_strategy: steps
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.0
    framework: huggingface
    huggingface_version: 4.37.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1709828799.390037
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 50
      - 51
      - 53
      - 55
      - 71
      - 98
      - 105
      2:
      - 1
      - 5
      - 11
      - 49
      - 50
      - 51
      - 53
      - 55
      - 71
      - 98
      - 105
      3:
      - 13
      - 16
      - 23
      4: 3.10.13
      5: 0.16.0
      6: 4.37.2
      8:
      - 5
      13: linux-x86_64
