hydra:
  run:
    dir: outputs

defaults:
  - model: mistral_7b_base
  - data: hh_rlhf_cai

wandb:
  project: scai
  log_model: checkpoint
  name: hh_ppo

ppo:
  beta: 0.1

training:
  evaluate_before_training: false
  n_epochs: 100
  lr: 1e-6
  train_batch_size: 1
  eval_batch_size: 1
  train_split: 0.9
  checkpoint_dir: /scr/jphilipp/scai/trained_models/Mistral-7B-v0.1/checkpoints/ppo
  max_grad_norm: 5.0
  num_warmup_steps: 150
  gradient_accumulation_steps: 8
  seed: 42
  model_archive: null #/scr/jphilipp/scai/trained_models/Mistral-7B-v0.1/checkpoints/cdpo/epoch-1/model.pt
