hydra:
  run:
    dir: outputs

defaults:
  - model: mistral_7b_ppo_vllm

model_archive: /scr/jphilipp/scai/trained_models/Mistral-7B-v0.1/checkpoints/ppo-beta-1.0-batch-size-32/epoch-0/model.pt

# '/scr/jphilipp/scai/trained_models/Mistral-7B-v0.1/merged/ppo-beta-1.0-batch-size-32/epoch-0