hydra:
  run:
    dir: outputs

defaults:
  - model: mistral_7b_base
  - data: hh_rlhf_cai

wandb:
  project: scai-with-labels
  log_model: checkpoint
  name: helpf-harml

ppo:
  beta: 0.0
  max_iter: 1
  loss: with_labels
  kl: per_token_kl

training:
  evaluate_before_training: false
  n_epochs: 1
  lr: 1e-6
  train_batch_size: 1
  eval_batch_size: 1
  train_split: 0.95
  checkpoint_dir: /scr/jphilipp/scai/trained_models/Mistral-7B-v0.1/checkpoints/ppo-beta-0.3-max-iter-1
  max_grad_norm: 2.0
  num_warmup_steps: 1
  gradient_accumulation_steps: 32
  save_after_n_steps: 500
  seed: 42
  model_archive: null #/scr/jphilipp/scai/trained_models/Mistral-7B-v0.1/checkpoints/cdpo/epoch-1/model.pt