hydra:
  run:
    dir: outputs

defaults:
  - model: mistral_7b_ppo_vllm

model_archive: /scr/jphilipp/scai/trained_models/Mistral-7B-v0.1/checkpoints/ppo-beta-0.5-max-iter-0/epoch-0.84/model.pt

# /scr/jphilipp/scai/trained_models/Mistral-7B-v0.1/merged/ppo-beta-0.5-max-iter-0/epoch-0.84