hydra:
  run:
    dir: outputs

defaults:
  - model: mistral_tiny_base
  - data: hh_rlhf_cai

wandb:
  project: scai
  log_model: checkpoint
  name: sft_hh_cdpo

training:
  n_epochs: 100
  lr: 1e-6
  train_batch_size: 1
  eval_batch_size: 1
  train_split: 1.0
  checkpoint_dir: ""
  # checkpoint_dir: "/scr/jphilipp/scai/trained_models/Mistral-7B-v0.1/checkpoints/cdpo_harmless"
  loss: "constitutional_dpo"
  num_training_steps: 3000
  max_grad_norm: 1.0
  num_warmup_steps: 150
  gradient_accumulation_steps: 1