hydra:
  run:
    dir: outputs

defaults:
  - model: mistral_7b_base
  - data: hh_rlhf_cai

wandb:
  project: hh-rlhf-kto
  name: kto



training_args:
  output_dir: /scr/jphilipp
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  gradient_accumulation_steps: 32
  learning_rate: 1e-6
  num_train_epochs: 1
  save_total_limit: 1
  evaluation_strategy: epoch
  seed: 42
  save_strategy: epoch
  report_to: wandb
  bf16: true
  lr_scheduler_type: cosine
  warmup_ratio: 0.1
  do_eval: true
  logging_steps: 1
  logging_strategy: steps
  max_prompt_length: 1024
  beta: 0.1
  max_length: 2048
