wandb_version: 1

model:
  desc: null
  value:
    model_type: huggingface
    name: mistral_7b_base
    model_config:
      pretrained_model_name_or_path: mistralai/Mistral-7B-v0.1
      cache_dir: /scr/jphilipp/scai/pretrained_models/Mistral-7B-v0.1
    tokenizer_config:
      pretrained_model_name_or_path: mistralai/Mistral-7B-v0.1
      cache_dir: /scr/jphilipp/scai/pretrained_models/Mistral-7B-v0.1
      model_max_length: 2048
data:
  desc: null
  value:
    data_path: /scr/jphilipp/scai/datasets/hh-rlhf-ppo-2/
    helpful: train-helpful-0-10k-v2.json
    harmless: train-harmless-0-10k-v2.json
    n_responses: 2
    n_constitutions: 2
wandb:
  desc: null
  value:
    project: scai-ppo-3
    log_model: checkpoint
    name: dpo-beta-0.1-iteration-1
dpo:
  desc: null
  value:
    beta: 0.1
train_split:
  desc: null
  value: 0.05
max_prompt_length:
  desc: null
  value: 512
training_args:
  desc: null
  value:
    output_dir: /scr/jphilipp/scai/trained_models/Mistral-7B-v0.1/checkpoints-no-icl/dpo-beta-0.1-iteration-1-0-2k
    per_device_train_batch_size: 1
    per_device_eval_batch_size: 1
    gradient_accumulation_steps: 32
    learning_rate: 1.0e-06
    num_train_epochs: 1
    save_total_limit: 1
    evaluation_strategy: epoch
    seed: 42
    save_strategy: epoch
    report_to: wandb
    bf16: true
    lr_scheduler_type: cosine
    warmup_ratio: 0.1
    do_eval: true
    logging_steps: 1
    logging_strategy: steps
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.0
    framework: huggingface
    huggingface_version: 4.37.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1709493863.120733
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 50
      - 51
      - 53
      - 55
      - 71
      - 84
      - 98
      - 105
      2:
      - 1
      - 5
      - 11
      - 49
      - 50
      - 51
      - 53
      - 55
      - 71
      - 84
      - 98
      - 105
      3:
      - 13
      - 16
      - 23
      4: 3.10.13
      5: 0.16.0
      6: 4.37.2
      8:
      - 5
      13: linux-x86_64
