wandb_version: 1

model:
  desc: null
  value:
    model_type: huggingface
    name: mistral_7b_base
    model_config:
      pretrained_model_name_or_path: /scr/jphilipp/scai/trained_models/Mistral-7B-v0.1/checkpoints/sft-iteration-1/checkpoint-365/
      cache_dir: /scr/jphilipp/scai/trained_models/Mistral-7B-v0.1/checkpoints/sft-iteration-1/checkpoint-365/
    tokenizer_config:
      pretrained_model_name_or_path: /scr/jphilipp/scai/trained_models/Mistral-7B-v0.1/checkpoints/sft-iteration-1/checkpoint-365/
      cache_dir: /scr/jphilipp/scai/trained_models/Mistral-7B-v0.1/checkpoints/sft-iteration-1/checkpoint-365/
      model_max_length: 2048
data:
  desc: null
  value:
    data_path: hh_rlhf/data
    helpful: train-helpful-0-10k-iteration-0-no-sorry-positive.json
    harmless: train-harmless-0-10k-iteration-0-no-sorry-positive.json
    n_responses: 2
    n_constitutions: 2
wandb:
  desc: null
  value:
    project: hh-rlhf-typo
    name: sft-typo-beta-0.1-iteration-1
pragpo:
  desc: null
  value:
    beta: 0.1
    include_kl_softmax: true
training:
  desc: null
  value:
    evaluate_before_training: false
    evaluate: false
    n_epochs: 1
    lr: 1.0e-06
    train_batch_size: 1
    eval_baftch_size: 1
    train_split: 1.0
    checkpoint_dir: /scr/jphilipp/scai/trained_models/Mistral-7B-v0.1/checkpoints/sft-typo-beta-0.1-iteration-1
    max_grad_norm: 1.0
    num_warmup_steps: 1
    gradient_accumulation_steps: 32
    save_after_n_steps: 500
    seed: 42
    model_archive: null
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.0
    framework: huggingface
    huggingface_version: 4.37.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1709834863.351983
    t:
      1:
      - 1
      - 11
      - 49
      - 50
      - 51
      - 55
      - 71
      - 105
      2:
      - 1
      - 11
      - 49
      - 50
      - 51
      - 55
      - 71
      - 105
      3:
      - 13
      - 16
      - 23
      4: 3.10.13
      5: 0.16.0
      6: 4.37.2
      8:
      - 5
      13: linux-x86_64
